Use tomllib on Python 3.11+
google/yapf pull request #1152
Opened 2023-09-24 11:59 UTC by felixonmars

Fallback to tomli for compatibility with older Python

2023-09-24 19:55 UTC, Spitfire1900 commented
Would you like to do similar for `importlib-metadata` as part of this PR? The PyPi package is only required on Python 3.7.

2023-09-24 20:21 UTC, Spitfire1900 commented on yapf/yapflib/file_resources.py
> -    import tomli as tomllib
Not a fan of nested try/catches in favor of https://peps.python.org/pep-0484/#version-and-platform-checking style approach.

I'm also wondering if moving the import to ./yapf/yapflib/__init__.py is a good idea idea vs. conditional login in every file.

Lastly, this package is now part of the package requirements, so managing an `ImportError` may no longer be applicable.

```python
import sys
if sys.version_info >= (3, 10):
    import tomllib
else:
    import tomli as tomllib
```

if ImportError must still be handled.
```python
import sys
if sys.version_info >= (3, 10):
    import tomllib
else:
    try:
        import tomli as tomllib
    except ImportError:
        raise errors.YapfError(
            'tomli package is needed for using pyproject.toml as a '
            'configuration file')
```

2023-09-28 14:50 UTC, Spitfire1900 requested changes
Use sys.version_info instead of nested try/catches.

Strip all import try/catches as tomli / tomllib is guaranteed by requirements specification.

2023-10-01 08:46 UTC, felixonmars commented
Looks like requested changes are in #1158 now. Closing in favor of that one.

2023-10-01 08:46 UTC, closed without merging